# AI ANIMATION BRIDGE MANIFESTO

schema_version = "1.0.0"

id = "ai_animation_bridge"
version = "1.0.0"
name = "AI Animation Bridge"
tagline = "Generate in-between animations using AI models"
maintainer = "Pluginowcy AGH <pluginowcy_agh@protonmail.com>"
type = "add-on"

website = "https://github.com/kottajl/blender-plug-in-for-modifying-3D-animations"

tags = ["Animation", "3D View"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

platforms = ["windows-x64", "macos-arm64", "linux-x64", "windows-arm64", "macos-x64"]

[permissions]
files = "Add new AI model"
network = "Download trained AI models"
clipboard = "Copy and paste 3D models"

[build]
paths_exclude_pattern = [
  "__pycache__/",
  "/.git/",
  "/.gitignore",
  "/*.zip",
  "/*.bat",
  "/*.sh",
  "/.DS_Store",
  "/*.blend1",
  "/*.blend",
  "/models/motion_inbetweening/experiments/lafan1_context_model_release/*.pth",
  "/models/motion_inbetweening/experiments/lafan1_context_model_release/*.pkl",
  "/models/motion_inbetweening/experiments/lafan1_detail_model_release/*.pth",
  "/models/motion_inbetweening/experiments/lafan1_detail_model_release/*.pkl",
  "/models/motion_inbetweening/datasets/lafan1/*.bvh",
  "/models/motion_inbetweening/datasets/lafan1/*.pkl",
  "/models/motion_inbetweening/output/*.bvh"
]
